// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from Cellbots.proto

package com.cellbots.cellserv.client;

import com.google.gwt.core.client.*;

public final class AudioVideoFrame extends JavaScriptObject  {

    public static final class Encoding extends JavaScriptObject {
            
        public static final Encoding JPEG = create(1);
        public static final Encoding H263 = create(2);
        public static final Encoding H264 = create(3);
        public static final Encoding MP3 = create(4);
        public static final Encoding AAC = create(5);
        public static final Encoding WAV = create(6);
        
        private static native Encoding create(int number) /*-{
            return number;
        }-*/;
        
        protected Encoding() {}
        
        public native int getNumber() /*-{
            return this;
        }-*/;
        
    }

    /**
     * Creates a new AudioVideoFrame instance 
     *
     * @return new AudioVideoFrame instance
     */
    public static native AudioVideoFrame create() /*-{
        return {
                        
        };
    }-*/;

    /**
     * Creates a new JsArray<AudioVideoFrame> instance 
     *
     * @return new JsArray<AudioVideoFrame> instance
     */
    public static native JsArray<AudioVideoFrame> createArray() /*-{
        return [];
    }-*/;

    /**
     * Gets a AudioVideoFrame (casting) from a JavaScriptObject
     *
     * @param JavaScriptObject to cast
     * @return AudioVideoFrame
     */
    public static native AudioVideoFrame get(JavaScriptObject jso) /*-{
        return jso;
    }-*/;
    
    /**
     * Gets a JsArray<AudioVideoFrame> (casting) from a JavaScriptObject
     *
     * @param JavaScriptObject to cast
     * @return JsArray<AudioVideoFrame> 
     */
    public static native JsArray<AudioVideoFrame> getArray(JavaScriptObject jso) /*-{
        return jso;
    }-*/;
    
    /**
     * Parses a AudioVideoFrame from a json string
     *
     * @param json string to be parsed/evaluated
     * @return AudioVideoFrame 
     */
    public static native AudioVideoFrame parse(String json) /*-{
        return $wnd.JSON.parse(json);
    }-*/;
    
    /**
     * Parses a JsArray<AudioVideoFrame> from a json string
     *
     * @param json string to be parsed/evaluated
     * @return JsArray<AudioVideoFrame> 
     */
    public static native JsArray<AudioVideoFrame> parseArray(String json) /*-{
        return $wnd.JSON.parse(json);
    }-*/;
    
    /**
     * Serializes a json object to a json string.
     *
     * @param AudioVideoFrame the object to serialize
     * @return String the serialized json string
     */
    public static native String stringify(AudioVideoFrame obj) /*-{
        return $wnd.JSON.stringify(obj);
    }-*/;
    
    public static native boolean isInitialized(AudioVideoFrame obj) /*-{
        return true;
    }-*/;
    
    protected AudioVideoFrame() {}

    // getters and setters

    // timestamp

    public native double getTimestamp() /*-{
        return this["timestamp"] || 0;
    }-*/;

    public native void setTimestamp(double timestamp) /*-{
        this["timestamp"] = timestamp;
    }-*/;

    public native void clearTimestamp() /*-{
        delete this["timestamp"];
    }-*/;

    public native boolean hasTimestamp() /*-{
        return this["timestamp"] != null;
    }-*/;

    // data

    public native String getData() /*-{
        return this["data"];
    }-*/;

    public native void setData(String data) /*-{
        this["data"] = data;
    }-*/;

    public native void clearData() /*-{
        delete this["data"];
    }-*/;

    public native boolean hasData() /*-{
        return this["data"] != null;
    }-*/;

    // frameNumber

    public native double getFrameNumber() /*-{
        return this["frameNumber"] || 0;
    }-*/;

    public native void setFrameNumber(double frameNumber) /*-{
        this["frameNumber"] = frameNumber;
    }-*/;

    public native void clearFrameNumber() /*-{
        delete this["frameNumber"];
    }-*/;

    public native boolean hasFrameNumber() /*-{
        return this["frameNumber"] != null;
    }-*/;

    // sourceID

    public native String getSourceID() /*-{
        return this["sourceID"] || "";
    }-*/;

    public native void setSourceID(String sourceID) /*-{
        this["sourceID"] = sourceID;
    }-*/;

    public native void clearSourceID() /*-{
        delete this["sourceID"];
    }-*/;

    public native boolean hasSourceID() /*-{
        return this["sourceID"] != null;
    }-*/;

    // whiteBalance

    public native int getWhiteBalance() /*-{
        return this["whiteBalance"] || 0;
    }-*/;

    public native void setWhiteBalance(int whiteBalance) /*-{
        this["whiteBalance"] = whiteBalance;
    }-*/;

    public native void clearWhiteBalance() /*-{
        delete this["whiteBalance"];
    }-*/;

    public native boolean hasWhiteBalance() /*-{
        return this["whiteBalance"] != null;
    }-*/;

    // zoomLevel

    public native int getZoomLevel() /*-{
        return this["zoomLevel"] || 0;
    }-*/;

    public native void setZoomLevel(int zoomLevel) /*-{
        this["zoomLevel"] = zoomLevel;
    }-*/;

    public native void clearZoomLevel() /*-{
        delete this["zoomLevel"];
    }-*/;

    public native boolean hasZoomLevel() /*-{
        return this["zoomLevel"] != null;
    }-*/;

    // compressionLevel

    public native int getCompressionLevel() /*-{
        return this["compressionLevel"] || 0;
    }-*/;

    public native void setCompressionLevel(int compressionLevel) /*-{
        this["compressionLevel"] = compressionLevel;
    }-*/;

    public native void clearCompressionLevel() /*-{
        delete this["compressionLevel"];
    }-*/;

    public native boolean hasCompressionLevel() /*-{
        return this["compressionLevel"] != null;
    }-*/;

    // widthPx

    public native int getWidthPx() /*-{
        return this["widthPx"] || 0;
    }-*/;

    public native void setWidthPx(int widthPx) /*-{
        this["widthPx"] = widthPx;
    }-*/;

    public native void clearWidthPx() /*-{
        delete this["widthPx"];
    }-*/;

    public native boolean hasWidthPx() /*-{
        return this["widthPx"] != null;
    }-*/;

    // heightPx

    public native int getHeightPx() /*-{
        return this["heightPx"] || 0;
    }-*/;

    public native void setHeightPx(int heightPx) /*-{
        this["heightPx"] = heightPx;
    }-*/;

    public native void clearHeightPx() /*-{
        delete this["heightPx"];
    }-*/;

    public native boolean hasHeightPx() /*-{
        return this["heightPx"] != null;
    }-*/;

    // timeSpan

    public native int getTimeSpan() /*-{
        return this["timeSpan"] || 0;
    }-*/;

    public native void setTimeSpan(int timeSpan) /*-{
        this["timeSpan"] = timeSpan;
    }-*/;

    public native void clearTimeSpan() /*-{
        delete this["timeSpan"];
    }-*/;

    public native boolean hasTimeSpan() /*-{
        return this["timeSpan"] != null;
    }-*/;

    // lightOn

    public native boolean getLightOn() /*-{
        return this["lightOn"] || false;
    }-*/;

    public native void setLightOn(boolean lightOn) /*-{
        this["lightOn"] = lightOn;
    }-*/;

    public native void clearLightOn() /*-{
        delete this["lightOn"];
    }-*/;

    public native boolean hasLightOn() /*-{
        return this["lightOn"] != null;
    }-*/;

    // encoding

    public native Encoding getEncoding() /*-{
        var v = this["encoding"];
        return v == null ? 1 : v;
    }-*/;

    public native void setEncoding(Encoding encoding) /*-{
        this["encoding"] = encoding;
    }-*/;

    public native void clearEncoding() /*-{
        delete this["encoding"];
    }-*/;

    public native boolean hasEncoding() /*-{
        return this["encoding"] != null;
    }-*/;

    // botID

    public native String getBotID() /*-{
        return this["botID"] || "";
    }-*/;

    public native void setBotID(String botID) /*-{
        this["botID"] = botID;
    }-*/;

    public native void clearBotID() /*-{
        delete this["botID"];
    }-*/;

    public native boolean hasBotID() /*-{
        return this["botID"] != null;
    }-*/;

}
