// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from Cellbots.proto

package com.cellbots.cellserv.client;

import com.google.gwt.core.client.*;

public final class PhoneState extends JavaScriptObject  {

    public static final class Compass extends JavaScriptObject  {

        /**
         * Creates a new Compass instance 
         *
         * @return new Compass instance
         */
        public static native Compass create() /*-{
            return {
                            
            };
        }-*/;

        /**
         * Creates a new JsArray<Compass> instance 
         *
         * @return new JsArray<Compass> instance
         */
        public static native JsArray<Compass> createArray() /*-{
            return [];
        }-*/;

        /**
         * Gets a Compass (casting) from a JavaScriptObject
         *
         * @param JavaScriptObject to cast
         * @return Compass
         */
        public static native Compass get(JavaScriptObject jso) /*-{
            return jso;
        }-*/;
        
        /**
         * Gets a JsArray<Compass> (casting) from a JavaScriptObject
         *
         * @param JavaScriptObject to cast
         * @return JsArray<Compass> 
         */
        public static native JsArray<Compass> getArray(JavaScriptObject jso) /*-{
            return jso;
        }-*/;
        
        /**
         * Parses a Compass from a json string
         *
         * @param json string to be parsed/evaluated
         * @return Compass 
         */
        public static native Compass parse(String json) /*-{
            return $wnd.JSON.parse(json);
        }-*/;
        
        /**
         * Parses a JsArray<Compass> from a json string
         *
         * @param json string to be parsed/evaluated
         * @return JsArray<Compass> 
         */
        public static native JsArray<Compass> parseArray(String json) /*-{
            return $wnd.JSON.parse(json);
        }-*/;
        
        /**
         * Serializes a json object to a json string.
         *
         * @param Compass the object to serialize
         * @return String the serialized json string
         */
        public static native String stringify(Compass obj) /*-{
            return $wnd.JSON.stringify(obj);
        }-*/;
        
        public static native boolean isInitialized(Compass obj) /*-{
            return true;
        }-*/;
        
        protected Compass() {}

        // getters and setters

        // x

        public native double getX() /*-{
            return this["x"] || 0;
        }-*/;

        public native void setX(double x) /*-{
            this["x"] = x;
        }-*/;

        public native void clearX() /*-{
            delete this["x"];
        }-*/;

        public native boolean hasX() /*-{
            return this["x"] != null;
        }-*/;

        // y

        public native double getY() /*-{
            return this["y"] || 0;
        }-*/;

        public native void setY(double y) /*-{
            this["y"] = y;
        }-*/;

        public native void clearY() /*-{
            delete this["y"];
        }-*/;

        public native boolean hasY() /*-{
            return this["y"] != null;
        }-*/;

        // z

        public native double getZ() /*-{
            return this["z"] || 0;
        }-*/;

        public native void setZ(double z) /*-{
            this["z"] = z;
        }-*/;

        public native void clearZ() /*-{
            delete this["z"];
        }-*/;

        public native boolean hasZ() /*-{
            return this["z"] != null;
        }-*/;

    }

    public static final class Accelerometer extends JavaScriptObject  {

        /**
         * Creates a new Accelerometer instance 
         *
         * @return new Accelerometer instance
         */
        public static native Accelerometer create() /*-{
            return {
                            
            };
        }-*/;

        /**
         * Creates a new JsArray<Accelerometer> instance 
         *
         * @return new JsArray<Accelerometer> instance
         */
        public static native JsArray<Accelerometer> createArray() /*-{
            return [];
        }-*/;

        /**
         * Gets a Accelerometer (casting) from a JavaScriptObject
         *
         * @param JavaScriptObject to cast
         * @return Accelerometer
         */
        public static native Accelerometer get(JavaScriptObject jso) /*-{
            return jso;
        }-*/;
        
        /**
         * Gets a JsArray<Accelerometer> (casting) from a JavaScriptObject
         *
         * @param JavaScriptObject to cast
         * @return JsArray<Accelerometer> 
         */
        public static native JsArray<Accelerometer> getArray(JavaScriptObject jso) /*-{
            return jso;
        }-*/;
        
        /**
         * Parses a Accelerometer from a json string
         *
         * @param json string to be parsed/evaluated
         * @return Accelerometer 
         */
        public static native Accelerometer parse(String json) /*-{
            return $wnd.JSON.parse(json);
        }-*/;
        
        /**
         * Parses a JsArray<Accelerometer> from a json string
         *
         * @param json string to be parsed/evaluated
         * @return JsArray<Accelerometer> 
         */
        public static native JsArray<Accelerometer> parseArray(String json) /*-{
            return $wnd.JSON.parse(json);
        }-*/;
        
        /**
         * Serializes a json object to a json string.
         *
         * @param Accelerometer the object to serialize
         * @return String the serialized json string
         */
        public static native String stringify(Accelerometer obj) /*-{
            return $wnd.JSON.stringify(obj);
        }-*/;
        
        public static native boolean isInitialized(Accelerometer obj) /*-{
            return true;
        }-*/;
        
        protected Accelerometer() {}

        // getters and setters

        // x

        public native double getX() /*-{
            return this["x"] || 0;
        }-*/;

        public native void setX(double x) /*-{
            this["x"] = x;
        }-*/;

        public native void clearX() /*-{
            delete this["x"];
        }-*/;

        public native boolean hasX() /*-{
            return this["x"] != null;
        }-*/;

        // y

        public native double getY() /*-{
            return this["y"] || 0;
        }-*/;

        public native void setY(double y) /*-{
            this["y"] = y;
        }-*/;

        public native void clearY() /*-{
            delete this["y"];
        }-*/;

        public native boolean hasY() /*-{
            return this["y"] != null;
        }-*/;

        // z

        public native double getZ() /*-{
            return this["z"] || 0;
        }-*/;

        public native void setZ(double z) /*-{
            this["z"] = z;
        }-*/;

        public native void clearZ() /*-{
            delete this["z"];
        }-*/;

        public native boolean hasZ() /*-{
            return this["z"] != null;
        }-*/;

    }

    public static final class Orientation extends JavaScriptObject  {

        /**
         * Creates a new Orientation instance 
         *
         * @return new Orientation instance
         */
        public static native Orientation create() /*-{
            return {
                            
            };
        }-*/;

        /**
         * Creates a new JsArray<Orientation> instance 
         *
         * @return new JsArray<Orientation> instance
         */
        public static native JsArray<Orientation> createArray() /*-{
            return [];
        }-*/;

        /**
         * Gets a Orientation (casting) from a JavaScriptObject
         *
         * @param JavaScriptObject to cast
         * @return Orientation
         */
        public static native Orientation get(JavaScriptObject jso) /*-{
            return jso;
        }-*/;
        
        /**
         * Gets a JsArray<Orientation> (casting) from a JavaScriptObject
         *
         * @param JavaScriptObject to cast
         * @return JsArray<Orientation> 
         */
        public static native JsArray<Orientation> getArray(JavaScriptObject jso) /*-{
            return jso;
        }-*/;
        
        /**
         * Parses a Orientation from a json string
         *
         * @param json string to be parsed/evaluated
         * @return Orientation 
         */
        public static native Orientation parse(String json) /*-{
            return $wnd.JSON.parse(json);
        }-*/;
        
        /**
         * Parses a JsArray<Orientation> from a json string
         *
         * @param json string to be parsed/evaluated
         * @return JsArray<Orientation> 
         */
        public static native JsArray<Orientation> parseArray(String json) /*-{
            return $wnd.JSON.parse(json);
        }-*/;
        
        /**
         * Serializes a json object to a json string.
         *
         * @param Orientation the object to serialize
         * @return String the serialized json string
         */
        public static native String stringify(Orientation obj) /*-{
            return $wnd.JSON.stringify(obj);
        }-*/;
        
        public static native boolean isInitialized(Orientation obj) /*-{
            return true;
        }-*/;
        
        protected Orientation() {}

        // getters and setters

        // azimuth

        public native double getAzimuth() /*-{
            return this["azimuth"] || 0;
        }-*/;

        public native void setAzimuth(double azimuth) /*-{
            this["azimuth"] = azimuth;
        }-*/;

        public native void clearAzimuth() /*-{
            delete this["azimuth"];
        }-*/;

        public native boolean hasAzimuth() /*-{
            return this["azimuth"] != null;
        }-*/;

        // pitch

        public native double getPitch() /*-{
            return this["pitch"] || 0;
        }-*/;

        public native void setPitch(double pitch) /*-{
            this["pitch"] = pitch;
        }-*/;

        public native void clearPitch() /*-{
            delete this["pitch"];
        }-*/;

        public native boolean hasPitch() /*-{
            return this["pitch"] != null;
        }-*/;

        // roll

        public native double getRoll() /*-{
            return this["roll"] || 0;
        }-*/;

        public native void setRoll(double roll) /*-{
            this["roll"] = roll;
        }-*/;

        public native void clearRoll() /*-{
            delete this["roll"];
        }-*/;

        public native boolean hasRoll() /*-{
            return this["roll"] != null;
        }-*/;

    }

    public static final class WIFI extends JavaScriptObject  {

        /**
         * Creates a new WIFI instance 
         *
         * @return new WIFI instance
         */
        public static native WIFI create() /*-{
            return {
                            
            };
        }-*/;

        /**
         * Creates a new JsArray<WIFI> instance 
         *
         * @return new JsArray<WIFI> instance
         */
        public static native JsArray<WIFI> createArray() /*-{
            return [];
        }-*/;

        /**
         * Gets a WIFI (casting) from a JavaScriptObject
         *
         * @param JavaScriptObject to cast
         * @return WIFI
         */
        public static native WIFI get(JavaScriptObject jso) /*-{
            return jso;
        }-*/;
        
        /**
         * Gets a JsArray<WIFI> (casting) from a JavaScriptObject
         *
         * @param JavaScriptObject to cast
         * @return JsArray<WIFI> 
         */
        public static native JsArray<WIFI> getArray(JavaScriptObject jso) /*-{
            return jso;
        }-*/;
        
        /**
         * Parses a WIFI from a json string
         *
         * @param json string to be parsed/evaluated
         * @return WIFI 
         */
        public static native WIFI parse(String json) /*-{
            return $wnd.JSON.parse(json);
        }-*/;
        
        /**
         * Parses a JsArray<WIFI> from a json string
         *
         * @param json string to be parsed/evaluated
         * @return JsArray<WIFI> 
         */
        public static native JsArray<WIFI> parseArray(String json) /*-{
            return $wnd.JSON.parse(json);
        }-*/;
        
        /**
         * Serializes a json object to a json string.
         *
         * @param WIFI the object to serialize
         * @return String the serialized json string
         */
        public static native String stringify(WIFI obj) /*-{
            return $wnd.JSON.stringify(obj);
        }-*/;
        
        public static native boolean isInitialized(WIFI obj) /*-{
            return true;
        }-*/;
        
        protected WIFI() {}

        // getters and setters

        // enabled

        public native boolean getEnabled() /*-{
            return this["enabled"] || false;
        }-*/;

        public native void setEnabled(boolean enabled) /*-{
            this["enabled"] = enabled;
        }-*/;

        public native void clearEnabled() /*-{
            delete this["enabled"];
        }-*/;

        public native boolean hasEnabled() /*-{
            return this["enabled"] != null;
        }-*/;

        // connected

        public native boolean getConnected() /*-{
            return this["connected"] || false;
        }-*/;

        public native void setConnected(boolean connected) /*-{
            this["connected"] = connected;
        }-*/;

        public native void clearConnected() /*-{
            delete this["connected"];
        }-*/;

        public native boolean hasConnected() /*-{
            return this["connected"] != null;
        }-*/;

        // strength

        public native int getStrength() /*-{
            return this["strength"] || 0;
        }-*/;

        public native void setStrength(int strength) /*-{
            this["strength"] = strength;
        }-*/;

        public native void clearStrength() /*-{
            delete this["strength"];
        }-*/;

        public native boolean hasStrength() /*-{
            return this["strength"] != null;
        }-*/;

        // kbps

        public native int getKbps() /*-{
            return this["kbps"] || 0;
        }-*/;

        public native void setKbps(int kbps) /*-{
            this["kbps"] = kbps;
        }-*/;

        public native void clearKbps() /*-{
            delete this["kbps"];
        }-*/;

        public native boolean hasKbps() /*-{
            return this["kbps"] != null;
        }-*/;

        // ssid

        public native int getSsid() /*-{
            return this["ssid"] || 0;
        }-*/;

        public native void setSsid(int ssid) /*-{
            this["ssid"] = ssid;
        }-*/;

        public native void clearSsid() /*-{
            delete this["ssid"];
        }-*/;

        public native boolean hasSsid() /*-{
            return this["ssid"] != null;
        }-*/;

        // ip

        public native int getIp() /*-{
            return this["ip"] || 0;
        }-*/;

        public native void setIp(int ip) /*-{
            this["ip"] = ip;
        }-*/;

        public native void clearIp() /*-{
            delete this["ip"];
        }-*/;

        public native boolean hasIp() /*-{
            return this["ip"] != null;
        }-*/;

        // chanel

        public native int getChanel() /*-{
            return this["chanel"] || 0;
        }-*/;

        public native void setChanel(int chanel) /*-{
            this["chanel"] = chanel;
        }-*/;

        public native void clearChanel() /*-{
            delete this["chanel"];
        }-*/;

        public native boolean hasChanel() /*-{
            return this["chanel"] != null;
        }-*/;

        // adhoc

        public native boolean getAdhoc() /*-{
            return this["adhoc"] || false;
        }-*/;

        public native void setAdhoc(boolean adhoc) /*-{
            this["adhoc"] = adhoc;
        }-*/;

        public native void clearAdhoc() /*-{
            delete this["adhoc"];
        }-*/;

        public native boolean hasAdhoc() /*-{
            return this["adhoc"] != null;
        }-*/;

    }

    public static final class Cellular extends JavaScriptObject  {

        /**
         * Creates a new Cellular instance 
         *
         * @return new Cellular instance
         */
        public static native Cellular create() /*-{
            return {
                            
            };
        }-*/;

        /**
         * Creates a new JsArray<Cellular> instance 
         *
         * @return new JsArray<Cellular> instance
         */
        public static native JsArray<Cellular> createArray() /*-{
            return [];
        }-*/;

        /**
         * Gets a Cellular (casting) from a JavaScriptObject
         *
         * @param JavaScriptObject to cast
         * @return Cellular
         */
        public static native Cellular get(JavaScriptObject jso) /*-{
            return jso;
        }-*/;
        
        /**
         * Gets a JsArray<Cellular> (casting) from a JavaScriptObject
         *
         * @param JavaScriptObject to cast
         * @return JsArray<Cellular> 
         */
        public static native JsArray<Cellular> getArray(JavaScriptObject jso) /*-{
            return jso;
        }-*/;
        
        /**
         * Parses a Cellular from a json string
         *
         * @param json string to be parsed/evaluated
         * @return Cellular 
         */
        public static native Cellular parse(String json) /*-{
            return $wnd.JSON.parse(json);
        }-*/;
        
        /**
         * Parses a JsArray<Cellular> from a json string
         *
         * @param json string to be parsed/evaluated
         * @return JsArray<Cellular> 
         */
        public static native JsArray<Cellular> parseArray(String json) /*-{
            return $wnd.JSON.parse(json);
        }-*/;
        
        /**
         * Serializes a json object to a json string.
         *
         * @param Cellular the object to serialize
         * @return String the serialized json string
         */
        public static native String stringify(Cellular obj) /*-{
            return $wnd.JSON.stringify(obj);
        }-*/;
        
        public static native boolean isInitialized(Cellular obj) /*-{
            return true;
        }-*/;
        
        protected Cellular() {}

        // getters and setters

        // enabled

        public native boolean getEnabled() /*-{
            return this["enabled"] || false;
        }-*/;

        public native void setEnabled(boolean enabled) /*-{
            this["enabled"] = enabled;
        }-*/;

        public native void clearEnabled() /*-{
            delete this["enabled"];
        }-*/;

        public native boolean hasEnabled() /*-{
            return this["enabled"] != null;
        }-*/;

        // connected

        public native boolean getConnected() /*-{
            return this["connected"] || false;
        }-*/;

        public native void setConnected(boolean connected) /*-{
            this["connected"] = connected;
        }-*/;

        public native void clearConnected() /*-{
            delete this["connected"];
        }-*/;

        public native boolean hasConnected() /*-{
            return this["connected"] != null;
        }-*/;

        // strength

        public native int getStrength() /*-{
            return this["strength"] || 0;
        }-*/;

        public native void setStrength(int strength) /*-{
            this["strength"] = strength;
        }-*/;

        public native void clearStrength() /*-{
            delete this["strength"];
        }-*/;

        public native boolean hasStrength() /*-{
            return this["strength"] != null;
        }-*/;

        // kbps

        public native int getKbps() /*-{
            return this["kbps"] || 0;
        }-*/;

        public native void setKbps(int kbps) /*-{
            this["kbps"] = kbps;
        }-*/;

        public native void clearKbps() /*-{
            delete this["kbps"];
        }-*/;

        public native boolean hasKbps() /*-{
            return this["kbps"] != null;
        }-*/;

        // ip

        public native int getIp() /*-{
            return this["ip"] || 0;
        }-*/;

        public native void setIp(int ip) /*-{
            this["ip"] = ip;
        }-*/;

        public native void clearIp() /*-{
            delete this["ip"];
        }-*/;

        public native boolean hasIp() /*-{
            return this["ip"] != null;
        }-*/;

        // roaming

        public native boolean getRoaming() /*-{
            return this["roaming"] || false;
        }-*/;

        public native void setRoaming(boolean roaming) /*-{
            this["roaming"] = roaming;
        }-*/;

        public native void clearRoaming() /*-{
            delete this["roaming"];
        }-*/;

        public native boolean hasRoaming() /*-{
            return this["roaming"] != null;
        }-*/;

    }

    public static final class Location extends JavaScriptObject  {

        /**
         * Creates a new Location instance 
         *
         * @return new Location instance
         */
        public static native Location create() /*-{
            return {
                            
            };
        }-*/;

        /**
         * Creates a new JsArray<Location> instance 
         *
         * @return new JsArray<Location> instance
         */
        public static native JsArray<Location> createArray() /*-{
            return [];
        }-*/;

        /**
         * Gets a Location (casting) from a JavaScriptObject
         *
         * @param JavaScriptObject to cast
         * @return Location
         */
        public static native Location get(JavaScriptObject jso) /*-{
            return jso;
        }-*/;
        
        /**
         * Gets a JsArray<Location> (casting) from a JavaScriptObject
         *
         * @param JavaScriptObject to cast
         * @return JsArray<Location> 
         */
        public static native JsArray<Location> getArray(JavaScriptObject jso) /*-{
            return jso;
        }-*/;
        
        /**
         * Parses a Location from a json string
         *
         * @param json string to be parsed/evaluated
         * @return Location 
         */
        public static native Location parse(String json) /*-{
            return $wnd.JSON.parse(json);
        }-*/;
        
        /**
         * Parses a JsArray<Location> from a json string
         *
         * @param json string to be parsed/evaluated
         * @return JsArray<Location> 
         */
        public static native JsArray<Location> parseArray(String json) /*-{
            return $wnd.JSON.parse(json);
        }-*/;
        
        /**
         * Serializes a json object to a json string.
         *
         * @param Location the object to serialize
         * @return String the serialized json string
         */
        public static native String stringify(Location obj) /*-{
            return $wnd.JSON.stringify(obj);
        }-*/;
        
        public static native boolean isInitialized(Location obj) /*-{
            return 
                obj["latitude"] != null 
                && obj["longitude"] != null;
        }-*/;
        
        protected Location() {}

        // getters and setters

        // accuracy

        public native double getAccuracy() /*-{
            return this["accuracy"] || 0;
        }-*/;

        public native void setAccuracy(double accuracy) /*-{
            this["accuracy"] = accuracy;
        }-*/;

        public native void clearAccuracy() /*-{
            delete this["accuracy"];
        }-*/;

        public native boolean hasAccuracy() /*-{
            return this["accuracy"] != null;
        }-*/;

        // altitude

        public native double getAltitude() /*-{
            return this["altitude"] || 0;
        }-*/;

        public native void setAltitude(double altitude) /*-{
            this["altitude"] = altitude;
        }-*/;

        public native void clearAltitude() /*-{
            delete this["altitude"];
        }-*/;

        public native boolean hasAltitude() /*-{
            return this["altitude"] != null;
        }-*/;

        // bearing

        public native double getBearing() /*-{
            return this["bearing"] || 0;
        }-*/;

        public native void setBearing(double bearing) /*-{
            this["bearing"] = bearing;
        }-*/;

        public native void clearBearing() /*-{
            delete this["bearing"];
        }-*/;

        public native boolean hasBearing() /*-{
            return this["bearing"] != null;
        }-*/;

        // latitude

        public native double getLatitude() /*-{
            return this["latitude"] || 0;
        }-*/;

        public native void setLatitude(double latitude) /*-{
            this["latitude"] = latitude;
        }-*/;

        public native void clearLatitude() /*-{
            delete this["latitude"];
        }-*/;

        public native boolean hasLatitude() /*-{
            return this["latitude"] != null;
        }-*/;

        // longitude

        public native double getLongitude() /*-{
            return this["longitude"] || 0;
        }-*/;

        public native void setLongitude(double longitude) /*-{
            this["longitude"] = longitude;
        }-*/;

        public native void clearLongitude() /*-{
            delete this["longitude"];
        }-*/;

        public native boolean hasLongitude() /*-{
            return this["longitude"] != null;
        }-*/;

        // provider

        public native String getProvider() /*-{
            return this["provider"] || "";
        }-*/;

        public native void setProvider(String provider) /*-{
            this["provider"] = provider;
        }-*/;

        public native void clearProvider() /*-{
            delete this["provider"];
        }-*/;

        public native boolean hasProvider() /*-{
            return this["provider"] != null;
        }-*/;

        // speed

        public native double getSpeed() /*-{
            return this["speed"] || 0;
        }-*/;

        public native void setSpeed(double speed) /*-{
            this["speed"] = speed;
        }-*/;

        public native void clearSpeed() /*-{
            delete this["speed"];
        }-*/;

        public native boolean hasSpeed() /*-{
            return this["speed"] != null;
        }-*/;

        // time

        public native double getTime() /*-{
            return this["time"] || 0;
        }-*/;

        public native void setTime(double time) /*-{
            this["time"] = time;
        }-*/;

        public native void clearTime() /*-{
            delete this["time"];
        }-*/;

        public native boolean hasTime() /*-{
            return this["time"] != null;
        }-*/;

    }

    /**
     * Creates a new PhoneState instance 
     *
     * @return new PhoneState instance
     */
    public static native PhoneState create() /*-{
        return {
                        
        };
    }-*/;

    /**
     * Creates a new JsArray<PhoneState> instance 
     *
     * @return new JsArray<PhoneState> instance
     */
    public static native JsArray<PhoneState> createArray() /*-{
        return [];
    }-*/;

    /**
     * Gets a PhoneState (casting) from a JavaScriptObject
     *
     * @param JavaScriptObject to cast
     * @return PhoneState
     */
    public static native PhoneState get(JavaScriptObject jso) /*-{
        return jso;
    }-*/;
    
    /**
     * Gets a JsArray<PhoneState> (casting) from a JavaScriptObject
     *
     * @param JavaScriptObject to cast
     * @return JsArray<PhoneState> 
     */
    public static native JsArray<PhoneState> getArray(JavaScriptObject jso) /*-{
        return jso;
    }-*/;
    
    /**
     * Parses a PhoneState from a json string
     *
     * @param json string to be parsed/evaluated
     * @return PhoneState 
     */
    public static native PhoneState parse(String json) /*-{
        return $wnd.JSON.parse(json);
    }-*/;
    
    /**
     * Parses a JsArray<PhoneState> from a json string
     *
     * @param json string to be parsed/evaluated
     * @return JsArray<PhoneState> 
     */
    public static native JsArray<PhoneState> parseArray(String json) /*-{
        return $wnd.JSON.parse(json);
    }-*/;
    
    /**
     * Serializes a json object to a json string.
     *
     * @param PhoneState the object to serialize
     * @return String the serialized json string
     */
    public static native String stringify(PhoneState obj) /*-{
        return $wnd.JSON.stringify(obj);
    }-*/;
    
    public static native boolean isInitialized(PhoneState obj) /*-{
        return 
            obj["timestamp"] != null;
    }-*/;
    
    protected PhoneState() {}

    // getters and setters

    // timestamp

    public native double getTimestamp() /*-{
        return this["timestamp"] || 0;
    }-*/;

    public native void setTimestamp(double timestamp) /*-{
        this["timestamp"] = timestamp;
    }-*/;

    public native void clearTimestamp() /*-{
        delete this["timestamp"];
    }-*/;

    public native boolean hasTimestamp() /*-{
        return this["timestamp"] != null;
    }-*/;

    // botID

    public native String getBotID() /*-{
        return this["botID"] || "";
    }-*/;

    public native void setBotID(String botID) /*-{
        this["botID"] = botID;
    }-*/;

    public native void clearBotID() /*-{
        delete this["botID"];
    }-*/;

    public native boolean hasBotID() /*-{
        return this["botID"] != null;
    }-*/;

    // dbgMsg

    public native String getDbgMsg() /*-{
        return this["dbgMsg"] || "";
    }-*/;

    public native void setDbgMsg(String dbgMsg) /*-{
        this["dbgMsg"] = dbgMsg;
    }-*/;

    public native void clearDbgMsg() /*-{
        delete this["dbgMsg"];
    }-*/;

    public native boolean hasDbgMsg() /*-{
        return this["dbgMsg"] != null;
    }-*/;

    // compass

    public native Compass getCompass() /*-{
        return this["compass"];
    }-*/;

    public native void setCompass(Compass compass) /*-{
        this["compass"] = compass;
    }-*/;

    public native void clearCompass() /*-{
        delete this["compass"];
    }-*/;

    public native boolean hasCompass() /*-{
        return this["compass"] != null;
    }-*/;

    // accelerometer

    public native Accelerometer getAccelerometer() /*-{
        return this["accelerometer"];
    }-*/;

    public native void setAccelerometer(Accelerometer accelerometer) /*-{
        this["accelerometer"] = accelerometer;
    }-*/;

    public native void clearAccelerometer() /*-{
        delete this["accelerometer"];
    }-*/;

    public native boolean hasAccelerometer() /*-{
        return this["accelerometer"] != null;
    }-*/;

    // orientation

    public native Orientation getOrientation() /*-{
        return this["orientation"];
    }-*/;

    public native void setOrientation(Orientation orientation) /*-{
        this["orientation"] = orientation;
    }-*/;

    public native void clearOrientation() /*-{
        delete this["orientation"];
    }-*/;

    public native boolean hasOrientation() /*-{
        return this["orientation"] != null;
    }-*/;

    // phoneBatteryLevel

    public native double getPhoneBatteryLevel() /*-{
        return this["phoneBatteryLevel"] || 0;
    }-*/;

    public native void setPhoneBatteryLevel(double phoneBatteryLevel) /*-{
        this["phoneBatteryLevel"] = phoneBatteryLevel;
    }-*/;

    public native void clearPhoneBatteryLevel() /*-{
        delete this["phoneBatteryLevel"];
    }-*/;

    public native boolean hasPhoneBatteryLevel() /*-{
        return this["phoneBatteryLevel"] != null;
    }-*/;

    // phoneBatteryTemp

    public native int getPhoneBatteryTemp() /*-{
        return this["phoneBatteryTemp"] || 0;
    }-*/;

    public native void setPhoneBatteryTemp(int phoneBatteryTemp) /*-{
        this["phoneBatteryTemp"] = phoneBatteryTemp;
    }-*/;

    public native void clearPhoneBatteryTemp() /*-{
        delete this["phoneBatteryTemp"];
    }-*/;

    public native boolean hasPhoneBatteryTemp() /*-{
        return this["phoneBatteryTemp"] != null;
    }-*/;

    // lightLevel

    public native double getLightLevel() /*-{
        return this["lightLevel"] || 0;
    }-*/;

    public native void setLightLevel(double lightLevel) /*-{
        this["lightLevel"] = lightLevel;
    }-*/;

    public native void clearLightLevel() /*-{
        delete this["lightLevel"];
    }-*/;

    public native boolean hasLightLevel() /*-{
        return this["lightLevel"] != null;
    }-*/;

    // vibrating

    public native boolean getVibrating() /*-{
        return this["vibrating"] || false;
    }-*/;

    public native void setVibrating(boolean vibrating) /*-{
        this["vibrating"] = vibrating;
    }-*/;

    public native void clearVibrating() /*-{
        delete this["vibrating"];
    }-*/;

    public native boolean hasVibrating() /*-{
        return this["vibrating"] != null;
    }-*/;

    // notificationLightOn

    public native boolean getNotificationLightOn() /*-{
        return this["notificationLightOn"] || false;
    }-*/;

    public native void setNotificationLightOn(boolean notificationLightOn) /*-{
        this["notificationLightOn"] = notificationLightOn;
    }-*/;

    public native void clearNotificationLightOn() /*-{
        delete this["notificationLightOn"];
    }-*/;

    public native boolean hasNotificationLightOn() /*-{
        return this["notificationLightOn"] != null;
    }-*/;

    // notificationLightFreq

    public native int getNotificationLightFreq() /*-{
        return this["notificationLightFreq"] || 0;
    }-*/;

    public native void setNotificationLightFreq(int notificationLightFreq) /*-{
        this["notificationLightFreq"] = notificationLightFreq;
    }-*/;

    public native void clearNotificationLightFreq() /*-{
        delete this["notificationLightFreq"];
    }-*/;

    public native boolean hasNotificationLightFreq() /*-{
        return this["notificationLightFreq"] != null;
    }-*/;

    // notificationLightColor

    public native int getNotificationLightColor() /*-{
        return this["notificationLightColor"] || 0;
    }-*/;

    public native void setNotificationLightColor(int notificationLightColor) /*-{
        this["notificationLightColor"] = notificationLightColor;
    }-*/;

    public native void clearNotificationLightColor() /*-{
        delete this["notificationLightColor"];
    }-*/;

    public native boolean hasNotificationLightColor() /*-{
        return this["notificationLightColor"] != null;
    }-*/;

    // proximity

    public native int getProximity() /*-{
        return this["proximity"] || 0;
    }-*/;

    public native void setProximity(int proximity) /*-{
        this["proximity"] = proximity;
    }-*/;

    public native void clearProximity() /*-{
        delete this["proximity"];
    }-*/;

    public native boolean hasProximity() /*-{
        return this["proximity"] != null;
    }-*/;

    // screenBrightness

    public native int getScreenBrightness() /*-{
        return this["screenBrightness"] || 0;
    }-*/;

    public native void setScreenBrightness(int screenBrightness) /*-{
        this["screenBrightness"] = screenBrightness;
    }-*/;

    public native void clearScreenBrightness() /*-{
        delete this["screenBrightness"];
    }-*/;

    public native boolean hasScreenBrightness() /*-{
        return this["screenBrightness"] != null;
    }-*/;

    // wifi

    public native WIFI getWifi() /*-{
        return this["wifi"];
    }-*/;

    public native void setWifi(WIFI wifi) /*-{
        this["wifi"] = wifi;
    }-*/;

    public native void clearWifi() /*-{
        delete this["wifi"];
    }-*/;

    public native boolean hasWifi() /*-{
        return this["wifi"] != null;
    }-*/;

    // cellular

    public native Cellular getCellular() /*-{
        return this["cellular"];
    }-*/;

    public native void setCellular(Cellular cellular) /*-{
        this["cellular"] = cellular;
    }-*/;

    public native void clearCellular() /*-{
        delete this["cellular"];
    }-*/;

    public native boolean hasCellular() /*-{
        return this["cellular"] != null;
    }-*/;

    // location

    public native Location getLocation() /*-{
        return this["location"];
    }-*/;

    public native void setLocation(Location location) /*-{
        this["location"] = location;
    }-*/;

    public native void clearLocation() /*-{
        delete this["location"];
    }-*/;

    public native boolean hasLocation() /*-{
        return this["location"] != null;
    }-*/;

    // gpsEnabled

    public native boolean getGpsEnabled() /*-{
        return this["gpsEnabled"] || false;
    }-*/;

    public native void setGpsEnabled(boolean gpsEnabled) /*-{
        this["gpsEnabled"] = gpsEnabled;
    }-*/;

    public native void clearGpsEnabled() /*-{
        delete this["gpsEnabled"];
    }-*/;

    public native boolean hasGpsEnabled() /*-{
        return this["gpsEnabled"] != null;
    }-*/;

    // hALConnection

    public native HALConnection getHALConnection() /*-{
        return this["hALConnection"];
    }-*/;

    public native void setHALConnection(HALConnection hALConnection) /*-{
        this["hALConnection"] = hALConnection;
    }-*/;

    public native void clearHALConnection() /*-{
        delete this["hALConnection"];
    }-*/;

    public native boolean hasHALConnection() /*-{
        return this["hALConnection"] != null;
    }-*/;

}
